# Site settings
title: Karmatr0n Home Page
email: karmatr0n@devnull.com
description: > # this means to ignore newlines until "baseurl:"
  Infosec, C, Objective C, C++, Ruby, iOS, OSX and Linux.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://karmatr0n.github.io" # the base hostname & protocol for your site
twitter_username: karmatr0n
github_username: karmatr0n

# Build settings
markdown: kramdown
