# Site settings
title: Karmatr0n
email: karmatr0n.dixit@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal blog. It is a place where I share ideas on topics I care about. Infosec, C, Objective C, C++, Ruby, Swift, iOS, OSX and Linux.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://karmatr0n.github.io" # the base hostname & protocol for your site
twitter_username: karmatr0n
github_username: karmatr0n

# Build settings
markdown: kramdown
permalink: pretty

